---
#logstash_listen_port_beats: 5044

kafka_out: false
kafka_in: false

logstash_elasticsearch_hosts:
  - http://localhost:9200

kafka_hosts: 
  - localhost:9092

kafka_topic: "test"

zookeeper_hosts: 
- localhost:2181

logstash_local_syslog_path: /var/log/syslog
logstash_monitor_local_syslog: true

logstash_ssl_dir: /etc/pki/logstash
logstash_ssl_certificate_file: ""
logstash_ssl_key_file: ""

logstash_enabled_on_boot: yes

logstash_install_plugins:
  - logstash-input-beats
  - logstash-codec-multiline
  - logstash-input-kafka
  - logstash-output-kafka
  - logstash-output-elasticsearch

#logstash_plugins_list:
#  - logstash-input-kinesis
