---

- name: Generate /etc/hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Configure zookeeper log and data directory
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
    mode: 0750
  with_items:
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_data_dir }}"

- name: ZOOKEEPER | Overwrite myid file.
  template:
    src: myid.j2
    dest: "{{zookeeper_conf_dir}}/conf/myid"
    force: "{{ zookeeper_force_myid }}"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Creating link for myid file.
  file:
    src: "{{zookeeper_conf_dir}}/conf/myid"
    dest: "{{zookeeper_data_dir}}/myid"
    state: link
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Overwrite default config file
  template:
    src: zoo.cfg.j2
    dest: "{{zookeeper_conf_dir}}/conf/zoo.cfg"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Configure zookeeper-env.sh
  template:
    src: zookeeper-env.sh.j2
    dest: "{{ zookeeper_conf_dir }}/conf/zookeeper-env.sh"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Configure zkEnv.sh
  template:
    src: zkEnv.sh.j2
    dest: "{{ zookeeper_dir }}/bin/zkEnv.sh"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper

- name: ZOOKEEPER | Update the log4j
  template:
    src: log4j.properties.j2
    dest: "{{ zookeeper_conf_dir }}/conf/log4j.properties"
    owner: "{{ zookeeper_user }}"
    group: "{{ zookeeper_group }}"
  notify:
    - Restart zookeeper
