---

- name: Download filebeat rpm package
  s3:
    bucket: elk-repo
    object: filebeat-6.2.4-x86_64.rpm
    dest: /opt/filebeat-6.2.4-x86_64.rpm
    mode: get

- name: Install the filebeat rpm package
  yum:
    name: /opt/filebeat-6.2.4-x86_64.rpm
    state: present
  notify:
    - Validate filebeat config
    - Restart filebeat
