--

- name: Download filebeat Deb package
  s3:
    bucket: elk-repo
    object: filebeat-6.2.4-amd64.deb
    dest: /opt/filebeat-6.2.4-amd64.deb  
    mode: get

- name: Install the filebeat Deb package
  apt:
    deb: /opt/filebeat-6.2.4-amd64.deb
  notify:
    - Validate filebeat config
    - Restart filebeat-

