---

- name: Download and install filebeat apt public signing key
  apt_key:
    url:   "{{ filebeat_signing_key_url }}"
    state: present

- name: Add filebeat apt repository definition to apt sources list
  apt_repository:
    repo:         "{{ filebeat_apt_repo }}"
    update_cache: yes
    state:        present

- name: Install filebeat ignoring "install-recommends"
  apt:
    name:  "filebeat={{ filebeat_version|default('*') }}"
    state: present
    install_recommends: no
  notify:
    - Validate filebeat config
    - Restart filebeat
