- name: Download elasticsearch rpm package
  s3:
    bucket: us-east-dev-us-tum-dev-elk
    object: elk-repo/elasticsearch-6.3.0.rpm
    dest: /opt/elasticsearch-6.3.0.rpm
    mode: get
  when: es_install_s3

- name: Install the elasticsearch rpm package
  yum:
    name: /opt/elasticsearch-6.3.0.rpm
    state: present
  notify: restart elasticsearch
  when: es_install_s3

