---
- name: Download elasticsearch deb package
  s3:
    bucket: elk-repo
    object: elasticsearch-6.3.0.deb
    dest: /opt/elasticsearch-6.3.0.deb
    mode: get
  when: es_install_s3
  notify: restart elasticsearch

- name: Install the elasticsearch deb package
  apt:
     deb: /opt/elasticsearch-6.3.0.deb
     state: present
  when: es_install_s3
  notify: restart elasticsearch
