---
- hosts: "ec2-52-23-236-139.compute-1.amazonaws.com"
  roles:
    - { role: elasticsearch, es_instance_name: "node1" }
  become: yes
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9201
 
