---
- name: Install Logstash
  hosts: "{{ hosts }}"
  become: true
  roles:
    - java
    - logstash
  vars:
   logstash_inputs: |
    kafka {
    bootstrap_servers => '172.31.91.145:9092,172.31.81.53:9092' #add the kafka hosts here
    topics => ["test"]
    codec => "json"
    }
   logstash_filters: |
    json {
    source => "message"
    skip_on_invalid_json => "true"
    }
   logstash_outputs: |
    elasticsearch {
    hosts => ["log-es-767366264.us-east-1.elb.amazonaws.com:80"]
    index => "log-%{+YYYY.MM.dd}"
    }

- hosts: master_nodes
  roles:
    - { role: elasticsearch, es_instance_name: node_master, 
    es_config: {
        discovery.zen.ping.unicast.hosts: "52.23.205.56:9300,18.205.160.73:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.memory_lock: true,
        cluster.name: "logging-es-cluster",
        network.host:  "0.0.0.0"
    	}
    }
  become: yes
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 512m
    es_api_port: 9201

- hosts: data_nodes
  roles:
    - { role: elasticsearch, es_instance_name: node_data,
    es_config: {
        discovery.zen.ping.unicast.hosts: "18.205.160.73:9300,52.23.205.56:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: true,
        cluster.name: "logging-es-cluster",
        network.host: "0.0.0.0"
    	}
    }
  become: yes
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 512m
    es_api_port: 9201


- hosts: kibana_hosts
  sudo : yes
  roles:
    - kibana
