- hosts: "{{ hosts }}"
  remote_user: ec-user
  become: yes
  roles:
    - role: filebeat
      filebeat_config: |
       filebeat.prospectors:
         - type: log
           paths:
             - /var/log/apache/access.log
             - /var/log/auth.log
       output.kafka:
         enabled: true
         hosts: "172.31.88.219:9092","172.31.83.62:9092"
         topic: test
