---
- name: Ensure kafka is ready to use
  hosts:  kafka_hosts
  remote_user: ec2-user
  become: yes
  roles:
    - {
          role: "kafka",
          kafka_hosts: ['35.171.22.132','52.90.61.201'],
          kafka_zookeeper_hosts: ['35.171.22.132','52.90.61.201'],
          kafka_version: 0.10.2.1,     # Kafka version override.
          kafka_scala_serverion: 2.12 # Scala version override.
      }
