---
- hosts: localhost
  become : yes
  remote_user: ubuntu
   
- roles:
    - java
    - { role: elasticsearch, es_instance_name: "node1" }
  become: yes
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9201
  - role : ansible-zookeeper
    - {
          role: "kafka",
          kafka_hosts: ['localhost'],
          kafka_zookeeper_hosts: ['localhost'],
          kafka_version: 0.10.2.1,     # Kafka version override.
          kafka_scala_serverion: 2.12 # Scala version override.
      }
    - logstash
    - kibana


