- name: Download Kibana Deb
  get_url:
    url: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm
    dest: /opt/
    mode: 0440

- name: install kibana rpm from a local file
  yum:
    name: /opt/kibana-{{ kibana_version }}-x86_64.rpm
    state: present
