#- name: Download Kibana Deb
#  get_url:
#    url: https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-x86_64.rpm
#    dest: /opt/
#    mode: 0440
#
#- name: install kibana rpm from a local file
#  yum:
#    name: /opt/kibana-{{ kibana_version }}-x86_64.rpm
#    state: present

- name: Download kibana rpm package
  s3:
    bucket: us-east-dev-us-tum-dev-elk
    object: elk-repo/kibana-6.3.0-x86_64.rpm
    dest: /opt/kibana-6.3.0-x86_64.rpm
    mode: get

- name: Install the kibana rpm package
  yum:
    name: /opt/kibana-6.3.0-x86_64.rpm
    state: present

