---
- name: Create Logstash configuration files.
  template:
    #src: "{{ item }}.j2"
    src: "logstash.conf.j2"
    dest: "/etc/logstash/conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - logstash.conf
  notify : restart logstash
