---

- name: Filebeat Install
  include: "install-{{ ansible_os_family|lower }}.yml"

- name: Create tmp dir for filebeat config fragments
  file:
    path:    "{{ filebeat_conf_fragments_dir }}"
    mode:    0755
    state:   directory
    #recurse: yes

- name: Ensure filebeat config directory exists
  file:
    path:   "{{ filebeat_conf_dir }}"
    owner:  root
    group:  root
    mode:   0755
    state:  directory

- name: Create filebeat prospectors and general config fragment
  template:
    src:  filebeat_frag.yml.j2
    dest: "{{ filebeat_conf_fragments_dir }}/10-filebeat.yml"

- name: Create filebeat outputs config fragment
  template:
    src:  outputs_frag.yml.j2
    dest: "{{ filebeat_conf_fragments_dir }}/20-outputs.yml"

- name: Create filebeat general config fragment
  template:
    src:  general_frag.yml.j2
    dest: "{{ filebeat_conf_fragments_dir }}/30-general.yml"

- name: Create filebeat logging config fragment
  template:
    src:  logging_frag.yml.j2
    dest: "{{ filebeat_conf_fragments_dir }}/40-logging.yml"

- name: Set filebeat config validate command | v5
  set_fact:
    filebeat_config_validate_cmd: "{{ filebeat_config_validate_cmd_v5 }}"
  when: filebeat_major_version == "5"

- name: Create filebeat config file from assembled config fragments
  assemble:
    src:   "{{ filebeat_conf_fragments_dir }}"
    dest:  "{{ filebeat_conf_dir }}/filebeat.yml"
    owner: root
    group: root
    mode:  0644
  notify:
    - Validate filebeat config
    - Restart filebeat

- name: Start filebeat
  service: name=filebeat enabled=yes state=started
